version: '3'
services:
  # PostgreSQL service
  postgres:
    image: postgres
    container_name: bs_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - phoenix-network

  # Phoenix app service
  phoenix_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phoenix_app
    environment:
      MIX_ENV: dev
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - phoenix-network

networks:
  phoenix-network:
    driver: bridge
